### PR TITLE
Change _toArray to Array.from

### PR DESCRIPTION
**Pull request by gotik**
non-public methods were removed from jsdom
https://github.com/tmpvar/jsdom/commit/08bc013da96bde74607cf7d6b9ff51a56e7931aa#diff-81c2dc6341007bd5871d83351cc7ede0L140

### CODE REVIEW

**Comment by luin** [comment]
Thank you for the pull request! It seems that `Array.from` is a feature of ES6, which is not available on the old node version (e.g. node 0.8).

**Comment by gotik** [comment]
I can change it to `Array.prototype.slice.call` but the issue this change is fixing is happening on the current version `2.0.0`, version that requires `iojs >= 2.0.0`.

The issue doesn't happen on the version `1` since it was introduced here https://github.com/luin/readability/commit/06336f04073f9ac82c66c08caa6ff996a70c5997
hence it shouldn't be a problem to use `Array.from`

I was checking the failing tests in this change but it seems like `master` has the issue causing the tests to fail :(

**Comment by luin** [comment]
Yes, I forgot it. Thanks again :laughing:

**Comment by luin** [comment]
Just submitted another pr to use slice instead since `Array.from` is not available in iojs v2.

**Comment by gotik** [comment]
You are right, I wish we could update the package's engine to node 4.0.0 :D

**Pull request merged**
