### PR TITLE
Replace text node followed by br with a p tag

### PR DESCRIPTION
**Pull request by wong2**
fix bad case: https://www.douban.com/group/topic/80835701/ where the article content is [removed](https://github.com/luin/readability/blob/master/src/helpers.js#L466) due to `p` tags are less than `img` tags, while there are actually lots of `<span>test</span><br>` inside the content.

@haroldtreen I think this should be a reasonable change

### CODE REVIEW

**Comment by haroldtreen** [comment]
Awesome! This seems reasonable.

Would it be possible to add a regression test for `douban.com` so that we ensure that the new content pulled in by this change isn't broken again in the future :). Not super urgent, but I think it's good to build up a suite of tests for any articles we fix.

https://github.com/luin/readability/blob/master/test/article-tests.js#L8

**Comment by wong2** [comment]
@haroldtreen no problem

**Comment by wong2** [comment]
@haroldtreen updated!

**Comment by wong2** [comment]
@haroldtreen will there be a new release soon?

**Comment by haroldtreen** [comment]
@wong2 I don't have access to the `npm` package unfortunately :(. 

I might have the ability to do a github release, but it might be confusing to have releases on Github not on `npm`. I personally have my `package.json` linked to the github master. 

@luin might be able to update the package though.

**Comment by wong2** [comment]
yeah the npm package hasn't been updated for a year, there should be a new release

**Comment by luin** [comment]
Sorry for the late response. Just released v3.0.0.

**Comment by wong2** [comment]
@luin great!

**Pull request merged**
