### PR TITLE
Title extraction from meta + regex fixes

### PR DESCRIPTION
**Pull request by haroldtreen**
## Changes:
- Update `getTitle` to check the meta tags for titles. (Twitter + Open Graph titles)
- Concatenate class and id with a newline. This allows you to match on things like `post` but only if it is at the start of the class/id.
- Update the regex to fix some sites that were failing to extract content.
- Add regression tests to check the extraction/title fixes.

## How to test:
- Run `npm test` with and without the helper changes to verify that they are fixing article extraction for the added tests.

Let me know if you have any questions/comments/concerns @luin :).

### CODE REVIEW

**Comment by haroldtreen** [comment]
Bump!
@luin

**Comment by haroldtreen** [comment]
Hey @luin. 

I submitted this over a month ago and there's been no response.
I'm feeling discouraged from continuing to contribute this repo as a result.

Can you let me know what you want to do with this?

**Comment by haroldtreen** [comment]
Thanks @luin :)

**Comment by luin** [comment]
Hi @haroldtreen. Sorry for the **very** late response! A little busy this month. I checked the code and it's awesome! Just merged it.

btw, I added you as a contributor of this repo. 😆

**Comment by haroldtreen** [comment]
Woot! Thanks @luin! :D

I'm actually going to a programming retreat in September and will be working on Open Source for 3 months. Content extraction has been a fun problem, so I'll probably have more to add. :)

**Pull request merged**
